#!/usr/bin/env node

const program = require('commander');

const pkg = require('./package.json');
const login = require('./commands/login');
const init = require('./commands/init');
const schema = require('./commands/schema');
const start = require('./commands/start');
const deploy = require('./commands/deploy');
const scale = require('./commands/scale');
const test = require('./commands/test');

program
  .version(pkg.version);

program
  .command('login')
  .description('log in to Restle')
  .action(login);

program
  .command('init <name>')
  .description('scaffolds a Restle application')
  .action(init);

program
  .command('schema <action> <type> [fields...]')
  .alias('schemas')
  .description('manage Restle schemas')
  .action(schema);

program
  .command('start')
  .option('-p, --port <port>', 'the port to run the instance on')
  .description('starts a Restle instance on localhost')
  .action(start);

program
  .command('deploy [dir]')
  .description('deploys a Restle instance')
  .action(deploy);

program
  .command('scale <number>')
  .description('scales the currently deployed Restle instance')
  .action(scale);

program
  .command('test <method> <endpoint>')
  .option('-s, --stress <rps>')
  .description('tests api endpoints of the currently reployed Reslte app')
  .action(test);

program.parse(process.argv);

const validCommands = /(init|schemas?|start|deploy|scale|login)/;
const command = process.argv[2];

if (!command || !validCommands.test(command)) program.help();
