#!/usr/bin/env node

const program = require('commander');

const pkg = require('./package');
const init = require('./tools/init');
const schema = require('./tools/schema');

program
  .version(pkg.version);

program
  .command('init')
  .action(init);

program
  .command('schema <action> <type> [fields...]')
  .alias('schemas')
  .option('-a, --attributes', 'schema attributes to add, update, or remove')
  .option('-r, --relationships', 'schema relationships to add, update, or remove')
  .description('add, update, or delete schemas')
  .action(schema);

program.parse(process.argv);

const validCommands = /(init|schemas?)/;
const command = process.argv[2];

if (!command || !validCommands.test(command)) program.help();
